# .github/workflows/ci-backend.yml

name: CI Backend

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04  # Specify the Ubuntu version explicitly

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment with pip caching
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'  # Enables pip caching

      # Step 3: Install dependencies
      - name: Install Dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock

      # Step 4: Run Linting with ruff
      - name: Lint with ruff
        working-directory: backend
        run: |
          ruff check api tests

      # Step 5: Run Tests with Pytest and Coverage
      - name: Run Pytest
        working-directory: backend
        run: |
          pytest --cov=api --cov=tests --cov-report=xml
